----
kind: pipeline
type: docker
name: test

steps:
- name: test
  image: node:alpine
  commands:
  - yarn
  - yarn test
  environment:
    PGUSER: postgres
    PGDATABASE: test
    PGHOST: database
    PGPASSWORD: sometest

services:
- name: database
  image: postgres:14-alpine
  environment:
    POSTGRES_USER: postgres
    POSTGRES_DB: test
    POSTGRES_PASSWORD: sometest
